### PR TITLE
vars: add ubuntu specific vars file as ubuntu cannot gracefully handle deps

### LINKED ISSUE #191: Unable to use with Ubuntu 18.04.
This playbook does  not work on Ubuntu 18.04 because the package  `gnupg2` is no longer available but is a dependency here https://github.com/cloudalchemy/ansible-grafana/blob/db9b5fb57a47ce8849c674094813892350028b1e/vars/debian.yml#L3-L8

According to [this comment on AskUbuntu](https://askubuntu.com/questions/748057/how-do-i-install-gnupg-2-0#comment1713081_748059) `gnupg` is `gnupg2` in Ubuntu 18.04, so for Ubuntu 18.04 (and possibly newer versions) `gnupg` could be installed. 

I changed the value in my local copy of the playbook and was able to install Grafana on Ubuntu 18.04.

### LINKED ISSUE #200: Installation fails due to missing package libfontconfig on Ubuntu 18.04
**What happened?**

This role fails with a recent Ubuntu 18.04 system:

```
$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
$ uname -r
4.15.0-76-generic
```

This is because `libfontconfig` has changed to `libfontconfig1`.
Running an `apt update` manually on the host before executing the role solves it.

Weirdly enough the role succeeds on a recent Debian system, even though though
it still requires `libfontconfig1`.

```
$ lsb_release -a
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
$ uname -r
4.19.0-6-amd64
```

```
$ apt install libfontconfig
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libfontconfig

# running apt update

$ apt install libfontconfig
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libfontconfig1' instead of 'libfontconfig'
The following additional packages will be installed:
  fontconfig-config fonts-dejavu-core
The following NEW packages will be installed:
  fontconfig-config fonts-dejavu-core libfontconfig1
```

**Did you expect to see some different?**

It should succeed.

**How to reproduce it (as minimally and precisely as possible)**:

Execute the role on a fresh Ubuntu 18.04 installation as target

**Environment**

* Role version:

```
0.16.1
```

* Ansible version information:

```
ansible 2.9.4
  config file = None
  configured module search path = ['/home/aknipping/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/aknipping/.local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
```

* Variables:

```
nothing relevant
```

* Ansible playbook execution Logs:

```
TASK [./roles/cloudalchemy.grafana : Install dependencies] ********************************************************************************
FAILED - RETRYING: Install dependencies (5 retries left).
FAILED - RETRYING: Install dependencies (4 retries left).
FAILED - RETRYING: Install dependencies (3 retries left).
FAILED - RETRYING: Install dependencies (2 retries left).
FAILED - RETRYING: Install dependencies (1 retries left).
fatal: [10.36.22.140]: FAILED! => {"attempts": 5, "changed": false, "msg": "No package matching 'libfontconfig' is available"}
```

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by paulfantom**
Fixes #200
Fixes #191 

I don't like this as it is not future-proof, but seems like this is currently the easiest way to fix some bugs on ubuntu systems.

### CODE REVIEW

**Comment by obitech** [comment]
I tried this patch locally and unfortunately it doesn't seem to work:

```
TASK [./roles/cloudalchemy.grafana : Install dependencies] *************************************************************************
FAILED - RETRYING: Install dependencies (5 retries left).
FAILED - RETRYING: Install dependencies (4 retries left).
FAILED - RETRYING: Install dependencies (3 retries left).
FAILED - RETRYING: Install dependencies (2 retries left).
FAILED - RETRYING: Install dependencies (1 retries left).
fatal: [10.36.22.140]: FAILED! => {"attempts": 5, "changed": false, "msg": "No package matching 'libfontconfig1' is available"}
```

What fixed it for me is to just update the apt cache before installing dependencies. Maybe we can just add in `tasks/install.yml`, before `Install dependencies`:

```yaml
---
- name: Update apt cache
  apt:
    update_cache: true
  register: _update_apt_cache
  until: _update_apt_cache is succeeded
  when:
    - ansible_pkg_mgr == "apt"

- name: Install dependencies
# ...
```

**Comment by paulfantom** [comment]
> What fixed it for me is to just update the apt cache before installing dependencies. Maybe we can just add in tasks/install.yml, before Install dependencies

I like it, can you create a PR?

**Comment by obitech** [comment]
> I like it, can you create a PR?

Of course! Have a look at #205 when you find some time 🙂

**Comment by obitech** [comment]
With #205 merged we can probably close this now or?

**Pull request closed without merging**
