### PR TITLE
Fix custom auth option not showing up

### PR DESCRIPTION
**Pull request by faxm0dem**
This completes the implementation of adding custom auth options.
See https://github.com/cloudalchemy/ansible-grafana/pull/219

### CODE REVIEW

**Comment by faxm0dem** [comment]
Sorry for forgetting this in the initial PR

**Comment by paulfantom** [comment]
@faxm0dem could you create a followup PR with a test scenario for this?

**Comment by faxm0dem** [comment]
Sorry, what do you mean by follow-up PR ?
And by test scenario do you mean a unit test ?

**Comment by paulfantom** [comment]
> Sorry, what do you mean by follow-up PR?

Just another PR as I merged this one :)

> And by test scenario do you mean a unit test?

More like integration test which could be put in https://github.com/cloudalchemy/ansible-grafana/tree/master/molecule/alternative to check if a custom auth option is showing and picked up by grafana.

**Comment by faxm0dem** [comment]
ah sorry, yeah sure I'll give it a shot

**Pull request merged**
