### PR TITLE
allow importing local dashboards

### LINKED ISSUE #54: Provision dashboards from file in addition to Grafana Dashboards
Currently dashboards can only be provisioned through their dashboard_id and downloaded from the Grafana Dashboards . It would be nice (and pretty simple to implement) if the dashboards can be supplied as a json file to the playbook

### PR DESCRIPTION
**Pull request by paulfantom**
Resolves #54

Just create `dashboards` directory on playbook level and drop your json dashboards there.

### CODE REVIEW

**Comment by boutetnico** [comment]
@paulfantom It would be nice to introduce a variable allowing one to customise the path to the `dashoards` directory. What do you think?

**Comment by boutetnico** [comment]
Also, local dashboards will not be copied to remote host unless `grafana_dashboards` is not empty. So we might want to update the conditional `when: grafana_dashboards | length > 0` in `tasks/main.yml` so that it's possible to install local dashboards only.

**Comment by paulfantom** [comment]
@boutetnico good catch! Fixed.

**Comment by paulfantom** [comment]
@boutetnico do you see any other problems with it?

**Comment by boutetnico** [comment]
@paulfantom I'm not able to have it fully working yet so I'm not sure.

However I'm wondering if `/tmp/dashboards` should be clean when it is created, in order to prevent copying files that are no more referenced but are still inside or files that were installed in a different Play for another host/inventory.

Also I had to change the following code to make it work on my infrastructure:

```yaml
- name: copy local grafana dashboards
  become: false
  copy:
    src: "{{ item }}.json"
    dest: "/tmp/dashboards/{{ item }}.json"
  with_fileglob:
    - "{{ grafana_dashboards_dir }}/*.json"
...
```

```yaml
- name: copy local grafana dashboards
  become: false
  copy:
    src: "{{ item }}"
    dest: "/tmp/dashboards/{{ item | basename }}"
  with_fileglob:
    - "{{ grafana_dashboards_dir }}/*.json"
...
```

**Comment by paulfantom** [comment]
> However I'm wondering if /tmp/dashboards should be clean when it is created

It could be done even better by using `tempfile` module, but it will also break ansible idempotance.

**Pull request merged**
